// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using life_copilot_kernel.Data;

#nullable disable

namespace life_copilot_kernel.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20240211122312_ChangeColumnType")]
    partial class ChangeColumnType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("life_copilot_kernel.Models.Action", b =>
                {
                    b.Property<Guid>("Action_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool?>("isDone")
                        .HasColumnType("boolean");

                    b.HasKey("Action_Id");

                    b.ToTable("Actions");
                });
#pragma warning restore 612, 618
        }
    }
}
